siteshortener/urls.py
from django.conf.urls import url, include
from siteshortener.views import index, redirect_original, shorten_url

app_name = "siteshortener"

urlpatterns = [
 
    url(r'^$', index, name='home'),
    # for our home/index page
 
    url(r'^(?P<short_id>\w{6})$', redirect_original, name='redirectoriginal'),
    # when short URL is requested it redirects to original URL
 
    url(r'^makeshort/$', shorten_url, name='shortenurl'),
    # this will create a URL's short id and return the short URL
]

urlshortener/urls.py
from django.contrib import admin
from django.conf.urls import url, include
# from django.urls import path

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    # if the URL pattern match /admin/ then open up admin panel

    url(r'', include('siteshortener.urls', namespace = 'siteshortener')),
    # if anything rather then /admin/ then it will look for shortenersite/urls
]

siteshortener/models.py
from __future__ import unicode_literals

from django.db import models

# Create your models here.
class Urls(models.Model):

    short_id = models.SlugField(max_length=6, primary_key = True)
    httpurl = models.URLField(max_length=200)
    pub_date = models.DateTimeField(auto_now=True)
    count = models.IntegerField(default=0)

    def __str__(self):
        return self.httpurl

siteshortener/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render

# Create your views here.
from django.shortcuts import render_to_response, get_object_or_404
import random, string, json
from siteshortener.models import Urls
from django.http import HttpResponseRedirect, HttpResponse
from django.conf import settings
# from django.core.context_processors import csrf
from django.views.decorators import csrf
from django.views.decorators.csrf import csrf_protect
from django.conf import settings
import socket
 
def index(request):
    c = {}
    # c.update(csrf(request))
    return render(request, 'siteshortener/index.html', c)
 
def redirect_original(request, short_id):
    url = get_object_or_404(Urls, pk=short_id) # get object, if not found return 404 error
    url.count += 1
    url.save()
    return HttpResponseRedirect(url.httpurl)
 
def shorten_url(request):
    url = request.POST.get("url", '')
    if not (url == ''):
        short_id = get_short_code()
        b = Urls(httpurl=url, short_id=short_id)
        b.save()
 
        response_data = {}
        # response_data['url'] = settings.SITE_URL + "/" + short_id
        response_data['url'] = "http://" + request.get_host() +  "/" + short_id
        return HttpResponse(json.dumps(response_data),  content_type="application/json")
    return HttpResponse(json.dumps({"error": "error occurs"}), content_type="application/json")
 
def get_short_code():
    length = 6
    char = string.ascii_uppercase + string.digits + string.ascii_lowercase
    # if the randomly generated short_id is used then generate next
    while True:
        short_id = ''.join(random.choice(char) for x in range(length))
        try:
            temp = Urls.objects.get(pk=short_id)
        except:
            return short_id

siteshortener/templates/siteshortener/base.html
<!DOCTYPE html>
<html>
    <head>
        <title>{% block title %}Bienvenido al sitio ReduceMe{% endblock %}</title>
        {% load staticfiles %}
		<script src="https://code.jquery.com/jquery-1.10.2.min.js"></script>
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
		<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
        <link rel="stylesheet" type="text/css" href="{% static 'siteshortener/css/custom.css' %}" />
        <script type="text/javascript" src="{% static 'siteshortener/js/script.js' %}"></script>
        <meta name="viewport" content="width=device-width, initial-scale=1">
    </head>
    <body>
        <div id="wrap">
            <header>
                <h1><a href="{% url 'siteshortener:home' %}">ReduceMe</a><p><small>Reduce tu URL</small></h1>
            </header>

            <div id="content">
                {% block content %}

                {% endblock %}
            </div>
        </div>
    </body>
</html>

siteshortener/templates/siteshortener/index.html
{% extends "siteshortener/base.html" %}

{% block title %}ReduceMe - ¡Reduce tu URL!{% endblock %}

{% block content %}

    <div class="panel panel-default">
        <div class="panel-body">
            <div class="col-sm-9">
                <input type="text" name="url" id="url" class="form-control input-sm" placeholder="http://www.ejemplo.com" />
            </div>
            <div class="col-sm-3">
                {% csrf_token %}
                <button id="submitButton" class="btn btn-primary">Reducir</button></p> 
            </div>
        </div>
        <div class="panel-footer">
            <span id="url-result"></span>
        </div>
        <div><h8>Ingresa tu URL arriba</div>
    </div>
{% endblock %}